In [25]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [27]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [31]:
x 

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [33]:
y

array([ 5, 20, 14, 32, 22, 38])

In [43]:
model = LinearRegression().fit(x, y)

In [61]:
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")
print(f"intercept: {model.intercept_}")

coefficient of determination: 0.715875613747954
intercept: 5.633333333333329


In [49]:
print(f"slope: {model.coef_}")

slope: [0.54]


In [51]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print(f"intercept: {new_model.intercept_}")

print(f"slope: {new_model.coef_}")


intercept: [5.63333333]
slope: [[0.54]]


In [53]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [55]:
y_pred = model.intercept_ + model.coef_ * x
print(f"predicted response:\n{y_pred}")

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [57]:
x_new = np.arange(5).reshape((-1, 1))
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [59]:
y_new = np.arange(5).reshape((-1, 1))
y_new

array([[0],
       [1],
       [2],
       [3],
       [4]])